scene: office0
deform_points: True
inherit_from: configs/Replica/replica.yaml
config_path: configs/Replica/office0.yaml
data:
  input_folder: datasets/Replica/office0
  output: output/Replica/office0
